spring:
  redis:
    host: localhost
    port: 6379
    password:
    ssl: false
    timeout: 10s
    database: 0
  task:
    scheduling:
      shutdown:
        await-termination-period: 30s
        await-termination: true

management.health.redis.enabled: true

spring-redis-streams-cleaner:
  transaction-repository:
    stream-name: transactions
  transaction-scheduler:
    max-length: 10
    cron: "*/30 * * * * *"
