spring:
  application:
    name: spring-redis-streams-consumer
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    ssl: ${REDIS_SSL}
    timeout: ${REDIS_TIMEOUT}
    database: ${REDIS_DATABASE}

management.health.redis.enabled: ${REDIS_HEALTHCHECK_ENABLED}

spring-redis-streams-consumer:
  transaction-repository:
    stream-name: ${TRANSACTION_REPOSITORY_STREAM_NAME}
    consumer-group: ${TRANSACTION_REPOSITORY_CONSUMER_GROUP}
    consumer-id: ${TRANSACTION_REPOSITORY_CONSUMER_ID}
  process-transaction:
    max-work-delay: ${PROCESS_TRANSACTION_MAX_WORK_DELAY}
